version: "3"

services:
  gungame:
    build:
      context: .
    environment:
      RCON_PASSWORD: mypass
    ports:
      - "27005:27005/udp"
      - "27015:27015/udp"
      - "27015:27015"
  hlstatsx:
    build:
      context: ./hlstatsx
    environment:
      DB_HOST: database
      DB_NAME: hlstatsxce
      DB_USER: hlstatsxce
      DB_PASSWORD: password
  database:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: hlstatsxce
      MYSQL_USER: hlstatsxce
      MYSQL_PASSWORD: password

volumes:
  db-data:
